# -*- coding: utf-8 -*-
"""Data Dummy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JHPHrdLm1bW5RLvQGcof21YuYKzdh7T4
"""

import pandas as pd
import random

# Fungsi untuk membuat data dummy produksi dan penjualan pabrik mainan
def create_production_and_sales_data(years, months, toys):
    toy_prices = {'Boneka': 50, 'Mobil-Mobilan': 65, 'Lego': 70, 'Action Figure': 125}  # Harga satuan barang

    data = []
    for year in years:
        for month in months:
            for toy in toys:
                production = random.randint(1000, 5000)  # Produksi acak antara 1000 hingga 5000 unit
                sales = random.randint(1000, 3000)  # Penjualan acak antara 200 hingga 1000 unit
                price_per_unit = toy_prices[toy]  # Harga satuan barang
                revenue = sales * price_per_unit  # Pendapatan berdasarkan harga satuan
                data.append({'Tahun': year, 'Bulan': month, 'Mainan': toy, 'Produksi': production, 'Penjualan': sales, 'Harga Satuan': price_per_unit, 'Pendapatan': revenue})
    return data

# Main function
if __name__ == "__main__":
    # Rentang tahun
    years = [2020, 2021, 2022, 2023]

    # Daftar bulan
    months = ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember']

    # Daftar mainan
    toys = ['Boneka', 'Mobil-Mobilan', 'Lego', 'Action Figure']

    # Membuat data dummy produksi dan penjualan
    data = create_production_and_sales_data(years, months, toys)

    # Konversi ke dataframe pandas
    df = pd.DataFrame(data)

    # Menyimpan data ke file CSV
    df.to_csv('Production_and_Sales.csv', index=False)

    print("Data dummy produksi dan penjualan pabrik mainan telah dibuat dan disimpan dalam file Production_and_Sales.csv")

df=pd.read_csv('/content/Production_and_Sales.csv')

df

